use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Component, Path};

use serde::Serialize;
use serde_json::{Map, Value};

use crate::{Error, OUTPUT_MARKER, OUTPUT_MARKER_CONTENT};

const HEADER: &str = "// Generated by MamboSite. Do not edit.\n";
const SUMMARY_FIELDS: &[&str] = &[
    "schemaVersion",
    "schema_version",
    "id",
    "route",
    "sourcePath",
    "source_path",
    "title",
    "description",
    "status",
    "listed",
    "date",
    "updated",
    "tags",
    "aliases",
    "order",
    "cover",
    "data",
    "children",
];

/// One path and its complete generated source.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

/// A complete managed output tree, sorted by normalized relative path.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedTree {
    files: Vec<GeneratedFile>,
}

impl GeneratedTree {
    /// Create a managed tree from generated files.
    ///
    /// The ownership marker is added automatically. Paths must be unique,
    /// case-insensitively unique, and remain below the tree root.
    ///
    /// # Errors
    ///
    /// Returns an error for unsafe, reserved, or colliding paths.
    pub fn new(files: impl IntoIterator<Item = GeneratedFile>) -> Result<Self, Error> {
        let mut output = vec![GeneratedFile {
            path: OUTPUT_MARKER.into(),
            contents: OUTPUT_MARKER_CONTENT.into(),
        }];
        for file in files {
            validate_generated_path(&file.path)?;
            output.push(file);
        }
        validate_collisions(&output)?;
        output.sort_by(|left, right| left.path.cmp(&right.path));
        Ok(Self { files: output })
    }

    pub fn files(&self) -> &[GeneratedFile] {
        &self.files
    }

    /// Add one generated file while preserving path invariants and sort order.
    ///
    /// # Errors
    ///
    /// Returns an error if the path is unsafe, reserved, or collides with an
    /// existing path.
    pub fn insert(&mut self, file: GeneratedFile) -> Result<(), Error> {
        validate_generated_path(&file.path)?;
        let folded = file.path.to_ascii_lowercase();
        if self.files.iter().any(|existing| {
            let existing = existing.path.to_ascii_lowercase();
            existing == folded
                || existing.starts_with(&format!("{folded}/"))
                || folded.starts_with(&format!("{existing}/"))
        }) {
            return Err(Error::DuplicatePath(file.path));
        }
        self.files.push(file);
        self.files.sort_by(|left, right| left.path.cmp(&right.path));
        Ok(())
    }
}

/// Backward-compatible name for the TypeScript site output tree.
pub type GeneratedSite = GeneratedTree;

struct PageModule {
    id: String,
    module_name: String,
    value: Value,
}

/// Convert a validated site model to deterministic TypeScript source in memory.
///
/// # Errors
///
/// Returns an error if serialization fails or the serialized model is not a
/// site object containing pages with unique, non-empty string IDs.
pub fn generate<T>(site: &T) -> Result<GeneratedTree, Error>
where
    T: Serialize,
{
    let mut root = serde_json::to_value(site)?;
    let root_object = root
        .as_object_mut()
        .ok_or_else(|| Error::InvalidSite("root value must be an object".into()))?;
    let page_values = root_object
        .remove("pages")
        .ok_or_else(|| Error::InvalidSite("root object is missing `pages`".into()))?;
    let pages = page_values
        .as_array()
        .ok_or_else(|| Error::InvalidSite("`pages` must be an array".into()))?;

    let mut modules = Vec::with_capacity(pages.len());
    let mut ids = BTreeSet::new();
    for page in pages {
        let object = page
            .as_object()
            .ok_or_else(|| Error::InvalidSite("every page must be an object".into()))?;
        let id = object
            .get("id")
            .and_then(Value::as_str)
            .filter(|id| !id.is_empty())
            .ok_or_else(|| Error::InvalidSite("every page needs a non-empty string `id`".into()))?
            .to_owned();
        if !ids.insert(id.clone()) {
            return Err(Error::DuplicatePageId(id));
        }
        modules.push(PageModule {
            module_name: module_name(&id),
            id,
            value: page.clone(),
        });
    }
    modules.sort_by(|left, right| left.id.cmp(&right.id));

    let summaries = modules
        .iter()
        .map(|module| page_summary(&module.value))
        .collect();
    root_object.insert("pages".into(), Value::Array(summaries));

    let mut files = Vec::with_capacity(modules.len() + 2);
    files.push(GeneratedFile {
        path: "manifest.ts".into(),
        contents: module_source(
            "SiteManifest",
            "manifest",
            &root,
            "export { manifest as default };\n",
        )?,
    });

    for module in &modules {
        files.push(GeneratedFile {
            path: format!("pages/{}.ts", module.module_name),
            contents: module_source(
                "PageRecord",
                "page",
                &module.value,
                "export default page;\n",
            )?,
        });
    }
    files.push(GeneratedFile {
        path: "pages/index.ts".into(),
        contents: page_index_source(&modules),
    });
    GeneratedTree::new(files)
}

fn validate_generated_path(value: &str) -> Result<(), Error> {
    let path = Path::new(value);
    let safe = !value.is_empty()
        && !value.contains('\\')
        && !path.is_absolute()
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_)));
    if !safe
        || path
            .components()
            .next()
            .is_some_and(|component| component.as_os_str() == OUTPUT_MARKER)
    {
        return Err(Error::InvalidGeneratedPath(value.to_owned()));
    }
    Ok(())
}

fn validate_collisions(files: &[GeneratedFile]) -> Result<(), Error> {
    let paths: BTreeSet<_> = files
        .iter()
        .map(|file| file.path.to_ascii_lowercase())
        .collect();
    if paths.len() != files.len() {
        return Err(Error::DuplicatePath(
            "case-insensitive generated path collision".to_owned(),
        ));
    }
    for path in &paths {
        let mut candidate = path.as_str();
        while let Some((parent, _)) = candidate.rsplit_once('/') {
            if paths.contains(parent) {
                return Err(Error::DuplicatePath(path.clone()));
            }
            candidate = parent;
        }
    }
    Ok(())
}

fn page_summary(page: &Value) -> Value {
    let Some(object) = page.as_object() else {
        return Value::Object(Map::new());
    };
    let summary = object
        .iter()
        .filter(|(key, _)| SUMMARY_FIELDS.contains(&key.as_str()))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    Value::Object(summary)
}

fn module_name(id: &str) -> String {
    if id
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
        && !matches!(id, "." | "..")
    {
        return id.to_owned();
    }

    let mut result = String::with_capacity(2 + id.len() * 2);
    result.push_str("p_");
    for byte in id.as_bytes() {
        let _ = write!(result, "{byte:02x}");
    }
    result
}

fn module_source(
    runtime_type: &str,
    binding: &str,
    value: &Value,
    exports: &str,
) -> Result<String, Error> {
    let json = safe_pretty_json(value)?;
    Ok(format!(
        "{HEADER}import type {{ {runtime_type} }} from \"@mambosite/runtime\";\n\nconst {binding} = {json} as const satisfies {runtime_type};\n\n{exports}"
    ))
}

fn page_index_source(modules: &[PageModule]) -> String {
    let mut output = String::from(HEADER);
    for (index, module) in modules.iter().enumerate() {
        let _ = writeln!(
            output,
            "import page{index} from \"./{}\";",
            module.module_name
        );
    }
    output.push_str("\nexport const pages = [");
    if !modules.is_empty() {
        output.push('\n');
        for index in 0..modules.len() {
            let _ = writeln!(output, "  page{index},");
        }
    }
    output.push_str("] as const;\n\nexport const pagesById = {\n");
    for index in 0..modules.len() {
        let _ = writeln!(output, "  [page{index}.id]: page{index},");
    }
    output.push_str("} as const;\n");
    output
}

fn safe_pretty_json(value: &Value) -> Result<String, Error> {
    let json = serde_json::to_string_pretty(value)?;
    // Both characters are valid JSON but historically terminate JavaScript
    // line literals in some parsers. Escaping them makes generated TS portable.
    Ok(json
        .replace('\u{2028}', "\\u2028")
        .replace('\u{2029}', "\\u2029"))
}

#[cfg(test)]
mod tests {
    use serde::Serialize;

    use super::*;

    #[derive(Serialize)]
    struct TestSite {
        schema_version: u32,
        pages: Vec<TestPage>,
    }

    #[derive(Serialize)]
    struct TestPage {
        id: String,
        route: String,
        title: String,
        body: Vec<String>,
    }

    fn site(ids: &[&str]) -> TestSite {
        TestSite {
            schema_version: 1,
            pages: ids
                .iter()
                .map(|id| TestPage {
                    id: (*id).into(),
                    route: format!("/{id}/"),
                    title: format!("{id} \"title\"\n</script>\u{2028}"),
                    body: vec!["content".into()],
                })
                .collect(),
        }
    }

    #[test]
    fn output_is_sorted_and_json_escaped() {
        let generated = generate(&site(&["p_b", "p_a"])).unwrap();
        let paths: Vec<_> = generated
            .files()
            .iter()
            .map(|file| file.path.as_str())
            .collect();
        assert_eq!(
            paths,
            [
                ".mambosite-generated",
                "manifest.ts",
                "pages/index.ts",
                "pages/p_a.ts",
                "pages/p_b.ts"
            ]
        );
        let page = generated
            .files()
            .iter()
            .find(|file| file.path == "pages/p_a.ts")
            .unwrap();
        assert!(page.contents.contains("\\\"title\\\"\\n</script>\\u2028"));
        let index = generated
            .files()
            .iter()
            .find(|file| file.path == "pages/index.ts")
            .unwrap();
        assert!(index.contents.find("./p_a").unwrap() < index.contents.find("./p_b").unwrap());
    }

    #[test]
    fn page_input_order_does_not_change_output() {
        let forward = generate(&site(&["p_a", "p_b"])).unwrap();
        let reverse = generate(&site(&["p_b", "p_a"])).unwrap();
        assert_eq!(forward, reverse);
    }

    #[test]
    fn manifest_omits_page_bodies() {
        let generated = generate(&site(&["p_a"])).unwrap();
        let manifest = generated
            .files()
            .iter()
            .find(|file| file.path == "manifest.ts")
            .unwrap();
        assert!(!manifest.contents.contains("\"body\""));
        assert!(manifest.contents.contains("\"route\": \"/p_a/\""));
    }

    #[test]
    fn rejects_duplicate_ids() {
        let error = generate(&site(&["same", "same"])).unwrap_err();
        assert!(matches!(error, Error::DuplicatePageId(id) if id == "same"));
    }

    #[test]
    fn rejects_case_insensitive_module_collisions() {
        let error = generate(&site(&["A", "a"])).unwrap_err();
        assert!(matches!(error, Error::DuplicatePath(_)));
    }

    #[test]
    fn encodes_ids_that_are_not_safe_file_names() {
        let generated = generate(&site(&["第二卷/path"])).unwrap();
        assert!(generated.files().iter().any(|file| {
            file.path.starts_with("pages/p_")
                && std::path::Path::new(&file.path)
                    .extension()
                    .is_some_and(|extension| extension.eq_ignore_ascii_case("ts"))
        }));
    }

    #[test]
    fn generated_trees_add_a_marker_and_accept_extra_files() {
        let mut tree = GeneratedTree::new([GeneratedFile {
            path: "theme.css".to_owned(),
            contents: ":root {}\n".to_owned(),
        }])
        .unwrap();
        tree.insert(GeneratedFile {
            path: "metadata/theme.ts".to_owned(),
            contents: "export {};\n".to_owned(),
        })
        .unwrap();

        assert_eq!(tree.files()[0].path, OUTPUT_MARKER);
        assert!(tree.files().iter().any(|file| file.path == "theme.css"));
        assert!(
            tree.files()
                .iter()
                .any(|file| file.path == "metadata/theme.ts")
        );
    }

    #[test]
    fn generated_trees_reject_unsafe_reserved_and_colliding_paths() {
        for path in [
            "",
            "../outside.ts",
            "/absolute.ts",
            "dir\\file.ts",
            OUTPUT_MARKER,
            ".mambosite-generated/child",
        ] {
            assert!(
                GeneratedTree::new([GeneratedFile {
                    path: path.to_owned(),
                    contents: String::new(),
                }])
                .is_err()
            );
        }

        let mut tree = GeneratedTree::new([GeneratedFile {
            path: "Theme.ts".to_owned(),
            contents: String::new(),
        }])
        .unwrap();
        assert!(
            tree.insert(GeneratedFile {
                path: "theme.ts".to_owned(),
                contents: String::new(),
            })
            .is_err()
        );
        assert!(
            tree.insert(GeneratedFile {
                path: "Theme.ts/child".to_owned(),
                contents: String::new(),
            })
            .is_err()
        );

        assert!(
            GeneratedTree::new([
                GeneratedFile {
                    path: "a".to_owned(),
                    contents: String::new(),
                },
                GeneratedFile {
                    path: "a-b".to_owned(),
                    contents: String::new(),
                },
                GeneratedFile {
                    path: "a/child.ts".to_owned(),
                    contents: String::new(),
                },
            ])
            .is_err()
        );
    }
}
