#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const provider = process.env.MAMBOCOLOUR_BIN ?? "mbcolor";
const output = join(root, "crates/mambosite-theme/src/mambo_colour.rs");
const check = process.argv.slice(2).includes("--check");

if (process.argv.slice(2).some((argument) => argument !== "--check")) {
  throw new Error("usage: node script/sync_mambocolour.mjs [--check]");
}

const temporary = mkdtempSync(join(tmpdir(), "mambosite-colour-"));

try {
  const orcheDark = generate("mamboorchedark");
  const orcheLight = generate("mamboorchelight");
  const outbackDark = generate("mambooutbackdark");
  const outbackLight = generate("mambooutbacklight");
  const source = render(
    palette(orcheDark, outbackDark, "dark"),
    palette(orcheLight, outbackLight, "light"),
  );

  if (check) {
    if (readFileSync(output, "utf8") !== source) {
      throw new Error("generated MamboColour theme is stale; run this command without --check");
    }
    console.log("MamboColour theme is current");
  } else {
    writeFileSync(output, source);
    console.log(`updated ${output}`);
  }
} finally {
  rmSync(temporary, { force: true, recursive: true });
}

function generate(name) {
  execFileSync(provider, [name, "css", "--out", temporary], {
    cwd: root,
    stdio: ["ignore", "ignore", "inherit"],
  });
  const source = readFileSync(join(temporary, `${name}.css`), "utf8");
  const values = new Map();

  for (const match of source.matchAll(/^\s+--([a-z0-9_]+):\s+#([0-9a-f]{6});$/gim)) {
    if (values.has(match[1])) throw new Error(`duplicate ${name} token: ${match[1]}`);
    values.set(match[1], `#${match[2].toLowerCase()}`);
  }
  if (values.size === 0) throw new Error(`MamboColour emitted no tokens for ${name}`);
  return values;
}

function token(values, name) {
  const value = values.get(name);
  if (!value) throw new Error(`MamboColour token is missing: ${name}`);
  return value;
}

function rgba(hex, alpha) {
  const channels = hex.slice(1).match(/../g).map((value) => Number.parseInt(value, 16));
  return `rgb(${channels.join(" ")} / ${alpha}%)`;
}

function palette(orche, outback, scheme) {
  const dark = scheme === "dark";
  const result = {
    background: token(orche, "bg"),
    surface: token(orche, "bg_surface"),
    surface_strong: token(orche, "border"),
    border: token(orche, "border"),
    text: token(orche, "fg"),
    text_muted: token(orche, "fg_muted"),
    text_subtle: token(orche, "comment"),
    brand: token(dark ? outback : orche, dark ? "magma_dust" : "brand"),
    brand_hover: token(dark ? outback : orche, dark ? "apricot_dust" : "brand_hover"),
    brand_active: token(outback, dark ? "wildfire" : "crimson_creek"),
    on_brand: token(orche, "bg"),
    selection: token(orche, "brand"),
    focus: token(orche, dark ? "warning" : "brand_hover"),
    success: token(orche, "success"),
    warning: token(orche, "warning"),
    danger: token(orche, "error"),
    header_background: rgba(token(orche, "bg"), 92),
    shadow: rgba(token(dark ? outback : orche, dark ? "dusty_parchment" : "fg"), dark ? 28 : 14),
    accents: [
      "shale_green",
      "apricot_dust",
      "desert_sage",
      "outback_sky",
      "burnt_ochre",
      "dusty_mauve",
    ].map((name) => token(outback, name)),
  };

  for (const name of ["brand", "brand_hover", "brand_active"]) {
    if (contrast(result[name], result.background) < 4.5 || contrast(result[name], result.on_brand) < 4.5) {
      throw new Error(`${scheme}.${name} does not meet 4.5:1 contrast`);
    }
  }
  if (contrast(result.focus, result.background) < 3) {
    throw new Error(`${scheme}.focus does not meet 3:1 contrast`);
  }
  return result;
}

function contrast(first, second) {
  const [lighter, darker] = [luminance(first), luminance(second)].sort((a, b) => b - a);
  return (lighter + 0.05) / (darker + 0.05);
}

function luminance(hex) {
  const channels = hex.slice(1).match(/../g).map((value) => Number.parseInt(value, 16) / 255);
  const [red, green, blue] = channels.map((value) =>
    value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4,
  );
  return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
}

function render(dark, light) {
  return [
    "// Generated by `node script/sync_mambocolour.mjs`; do not edit.",
    "// Source: MamboColour's positional `css` provider command.",
    "",
    "use crate::model::ColorPalette;",
    "",
    renderPalette("dark", dark),
    "",
    renderPalette("light", light),
    "",
  ].join("\n");
}

function renderPalette(name, values) {
  const fields = Object.entries(values)
    .filter(([field]) => field !== "accents")
    .map(([field, value]) => `        ${field}: ${JSON.stringify(value)}.to_owned(),`);
  const accents = values.accents.map((value) => JSON.stringify(value)).join(", ");
  return [
    `pub(crate) fn ${name}() -> ColorPalette {`,
    "    ColorPalette {",
    ...fields,
    "        accents: [",
    `            ${accents},`,
    "        ]",
    "        .map(str::to_owned)",
    "        .to_vec(),",
    "    }",
    "}",
  ].join("\n");
}
