use std::fmt::Write as _;

use crate::model::{
    ColorPalette, ColorScheme, HeaderMode, Responsive, SidebarMode, TextStyle, Theme,
};

#[derive(Clone, Copy)]
enum Point {
    Compact,
    Content,
    Wide,
}

impl Point {
    const fn name(self) -> &'static str {
        match self {
            Self::Compact => "compact",
            Self::Content => "content",
            Self::Wide => "wide",
        }
    }
}

pub(crate) fn render(theme: &Theme) -> String {
    let mut css = String::from("/* Generated by MamboSite. Do not edit. */\n\n");
    for face in &theme.fonts.faces {
        writeln!(css, "@font-face {{").unwrap();
        writeln!(css, "  font-family: \"{}\";", quoted(&face.family)).unwrap();
        writeln!(
            css,
            "  src: url(\"{}\") format(\"{}\");",
            quoted(&face.source),
            face.format.as_css()
        )
        .unwrap();
        writeln!(css, "  font-weight: {};", face.weight).unwrap();
        writeln!(css, "  font-style: {};", face.style.as_css()).unwrap();
        writeln!(css, "  font-display: {};", face.display.as_css()).unwrap();
        writeln!(css, "}}\n").unwrap();
    }

    let default_palette = palette(theme, theme.default_scheme);
    writeln!(
        css,
        ":root,\n[data-theme=\"{}\"] {{",
        theme.default_scheme.as_str()
    )
    .unwrap();
    write_palette(&mut css, theme.default_scheme, default_palette);
    writeln!(css, "}}\n").unwrap();

    for scheme in [ColorScheme::Dark, ColorScheme::Light] {
        if scheme == theme.default_scheme {
            continue;
        }
        writeln!(css, "[data-theme=\"{}\"] {{", scheme.as_str()).unwrap();
        write_palette(&mut css, scheme, palette(theme, scheme));
        writeln!(css, "}}\n").unwrap();
    }

    writeln!(css, ":root {{").unwrap();
    write_base_tokens(&mut css, theme);
    writeln!(css, "}}\n").unwrap();
    write_collection_rules(
        &mut css,
        "",
        *theme.components.collection.max_columns.base(),
    );
    write_base_columns_rules(&mut css);

    for (point, width) in [
        (Point::Compact, theme.breakpoints.compact),
        (Point::Content, theme.breakpoints.content),
        (Point::Wide, theme.breakpoints.wide),
    ] {
        let declarations = responsive_declarations(theme, point);
        writeln!(css, "@media (min-width: {width}px) {{").unwrap();
        if !declarations.is_empty() {
            writeln!(css, "  :root {{").unwrap();
            for (name, value) in declarations {
                writeln!(css, "    --mambo-{name}: {value};").unwrap();
            }
            writeln!(css, "  }}").unwrap();
        }
        write_collection_rules(&mut css, "  ", collection_limit_at(theme, point));
        write_columns_breakpoint_rule(&mut css, point);
        writeln!(css, "}}\n").unwrap();
    }

    css
}

fn palette(theme: &Theme, scheme: ColorScheme) -> &ColorPalette {
    match scheme {
        ColorScheme::Dark => &theme.colors.dark,
        ColorScheme::Light => &theme.colors.light,
    }
}

fn write_palette(css: &mut String, scheme: ColorScheme, palette: &ColorPalette) {
    writeln!(css, "  color-scheme: {};", scheme.as_str()).unwrap();
    for (name, value) in [
        ("background", &palette.background),
        ("surface", &palette.surface),
        ("surface-strong", &palette.surface_strong),
        ("border", &palette.border),
        ("text", &palette.text),
        ("text-muted", &palette.text_muted),
        ("text-subtle", &palette.text_subtle),
        ("brand", &palette.brand),
        ("brand-hover", &palette.brand_hover),
        ("on-brand", &palette.on_brand),
        ("selection", &palette.selection),
        ("focus", &palette.focus),
        ("success", &palette.success),
        ("warning", &palette.warning),
        ("danger", &palette.danger),
        ("header-background", &palette.header_background),
        ("shadow", &palette.shadow),
    ] {
        writeln!(css, "  --mambo-color-{name}: {value};").unwrap();
    }
    for (index, accent) in palette.accents.iter().enumerate() {
        writeln!(css, "  --mambo-color-accent-{}: {accent};", index + 1).unwrap();
    }
}

fn write_base_tokens(css: &mut String, theme: &Theme) {
    for (name, value) in [
        ("font-body", theme.fonts.body.as_str()),
        ("font-heading", theme.fonts.heading.as_str()),
        ("font-mono", theme.fonts.mono.as_str()),
    ] {
        declaration(css, name, value);
    }

    for (name, style) in typography(theme) {
        declaration(css, &format!("type-{name}-size"), style.size.base());
        declaration(css, &format!("type-{name}-line-height"), &style.line_height);
        declaration(css, &format!("type-{name}-weight"), style.weight);
        declaration(
            css,
            &format!("type-{name}-letter-spacing"),
            &style.letter_spacing,
        );
    }

    for (name, value) in [
        ("space-xxs", &theme.spacing.xxs),
        ("space-xs", &theme.spacing.xs),
        ("space-sm", &theme.spacing.sm),
        ("space-md", &theme.spacing.md),
        ("space-lg", &theme.spacing.lg),
        ("space-xl", &theme.spacing.xl),
        ("space-xxl", &theme.spacing.xxl),
        ("space-section", &theme.spacing.section),
        ("width-reading", &theme.widths.reading),
        ("width-normal", &theme.widths.normal),
        ("width-wide", &theme.widths.wide),
        ("width-full", &theme.widths.full),
        ("width-shell", &theme.widths.shell),
        ("width-sidebar", &theme.widths.sidebar),
        ("width-card-min", &theme.widths.card_min),
        ("width-hero-image-min", &theme.widths.hero_image_min),
        (
            "dimension-main-top-padding",
            theme.dimensions.main_top_padding.base(),
        ),
        (
            "dimension-header-height",
            theme.dimensions.header_height.base(),
        ),
        ("dimension-header-blur", &theme.dimensions.header_blur),
        ("dimension-toc-offset", theme.dimensions.toc_offset.base()),
        (
            "dimension-hero-min-height",
            &theme.dimensions.hero_min_height,
        ),
        (
            "dimension-control-min-height",
            &theme.dimensions.control_min_height,
        ),
        ("border-thin", &theme.borders.thin),
        ("border-strong", &theme.borders.strong),
        ("border-accent", &theme.borders.accent),
        ("radius-small", &theme.radii.small),
        ("radius-medium", &theme.radii.medium),
        ("radius-large", &theme.radii.large),
        ("radius-pill", &theme.radii.pill),
        ("shadow-small", &theme.shadows.small),
        ("shadow-medium", &theme.shadows.medium),
        ("shadow-large", &theme.shadows.large),
        ("motion-fast", &theme.motion.fast),
        ("motion-normal", &theme.motion.normal),
        ("motion-slow", &theme.motion.slow),
        ("motion-easing", &theme.motion.easing),
    ] {
        declaration(css, name, value);
    }
    declaration(css, "border-style", theme.borders.style.as_css());

    write_base_layout_tokens(css, theme);
}

fn write_base_layout_tokens(css: &mut String, theme: &Theme) {
    for (name, value) in [
        (
            "layout-page-with-sidebar-columns",
            theme.layout.page_with_sidebar_columns.base(),
        ),
        (
            "layout-hero-split-columns",
            theme.layout.hero_split_columns.base(),
        ),
        (
            "layout-list-card-columns",
            theme.layout.list_card_columns.base(),
        ),
        (
            "layout-metadata-columns",
            theme.layout.metadata_columns.base(),
        ),
        (
            "layout-header-inline-padding",
            theme.layout.header_inline_padding.base(),
        ),
        (
            "layout-page-inline-padding",
            theme.layout.page_inline_padding.base(),
        ),
        (
            "layout-footer-inline-padding",
            theme.layout.footer_inline_padding.base(),
        ),
    ] {
        declaration(css, name, value);
    }
    declaration(
        css,
        "layout-footer-direction",
        theme.layout.footer_direction.base().as_css(),
    );

    declaration(
        css,
        "collection-max-columns",
        theme.components.collection.max_columns.base(),
    );
    write_sidebar(css, *theme.components.sidebar.mode.base());
    write_header_mode(css, *theme.components.header.mode.base());
    declaration(
        css,
        "header-clock-display",
        theme.components.header.clock.base().flex_display(),
    );
    declaration(
        css,
        "header-hide-on-scroll",
        u8::from(theme.components.header.hide_on_scroll),
    );
    declaration(css, "header-hide-after", theme.components.header.hide_after);
}

fn responsive_declarations(theme: &Theme, point: Point) -> Vec<(String, String)> {
    let mut declarations = Vec::new();
    for (name, style) in typography(theme) {
        push_override(
            &mut declarations,
            format!("type-{name}-size"),
            &style.size,
            point,
            ToString::to_string,
        );
    }
    for (name, value) in [
        (
            "dimension-main-top-padding",
            &theme.dimensions.main_top_padding,
        ),
        ("dimension-header-height", &theme.dimensions.header_height),
        ("dimension-toc-offset", &theme.dimensions.toc_offset),
        (
            "layout-page-with-sidebar-columns",
            &theme.layout.page_with_sidebar_columns,
        ),
        (
            "layout-hero-split-columns",
            &theme.layout.hero_split_columns,
        ),
        ("layout-list-card-columns", &theme.layout.list_card_columns),
        ("layout-metadata-columns", &theme.layout.metadata_columns),
        (
            "layout-header-inline-padding",
            &theme.layout.header_inline_padding,
        ),
        (
            "layout-page-inline-padding",
            &theme.layout.page_inline_padding,
        ),
        (
            "layout-footer-inline-padding",
            &theme.layout.footer_inline_padding,
        ),
    ] {
        push_override(
            &mut declarations,
            name.to_owned(),
            value,
            point,
            ToString::to_string,
        );
    }
    push_override(
        &mut declarations,
        "collection-max-columns".to_owned(),
        &theme.components.collection.max_columns,
        point,
        ToString::to_string,
    );
    if let Some(mode) = at(&theme.components.sidebar.mode, point) {
        declarations.push(("sidebar-display".to_owned(), mode.display().to_owned()));
        declarations.push(("sidebar-position".to_owned(), mode.position().to_owned()));
        declarations.push(("sidebar-order".to_owned(), mode.order().to_string()));
    }
    if let Some(mode) = at(&theme.components.header.mode, point) {
        declarations.push(("header-display".to_owned(), mode.display().to_owned()));
        declarations.push(("header-grid-template".to_owned(), mode.columns().to_owned()));
    }
    if let Some(visibility) = at(&theme.components.header.clock, point) {
        declarations.push((
            "header-clock-display".to_owned(),
            visibility.flex_display().to_owned(),
        ));
    }
    if let Some(direction) = at(&theme.layout.footer_direction, point) {
        declarations.push((
            "layout-footer-direction".to_owned(),
            direction.as_css().to_owned(),
        ));
    }
    declarations
}

fn write_collection_rules(css: &mut String, indent: &str, maximum: u8) {
    for requested in 1..=6 {
        let effective = requested.min(maximum);
        writeln!(
            css,
            "{indent}[data-mambo-collection][data-columns=\"{requested}\"] {{ --mambo-collection-columns: {effective}; }}"
        )
        .unwrap();
    }
    writeln!(css).unwrap();
}

fn write_base_columns_rules(css: &mut String) {
    writeln!(
        css,
        "[data-mambo-columns][data-collapse=\"compact\"],\n[data-mambo-columns][data-collapse=\"content\"],\n[data-mambo-columns][data-collapse=\"wide\"] {{\n  --mambo-layout-columns-template: minmax(0, 1fr);\n}}"
    )
    .unwrap();
    writeln!(
        css,
        "[data-mambo-columns][data-collapse=\"never\"] {{\n  --mambo-layout-columns-template: repeat(var(--mambo-column-count, 2), minmax(0, 1fr));\n}}\n"
    )
    .unwrap();
}

fn write_columns_breakpoint_rule(css: &mut String, point: Point) {
    writeln!(
        css,
        "  [data-mambo-columns][data-collapse=\"{}\"] {{",
        point.name()
    )
    .unwrap();
    writeln!(
        css,
        "    --mambo-layout-columns-template: repeat(var(--mambo-column-count, 2), minmax(0, 1fr));"
    )
    .unwrap();
    writeln!(css, "  }}").unwrap();
}

fn collection_limit_at(theme: &Theme, point: Point) -> u8 {
    let responsive = &theme.components.collection.max_columns;
    match point {
        Point::Compact => responsive.compact().copied().unwrap_or(*responsive.base()),
        Point::Content => responsive
            .content()
            .or_else(|| responsive.compact())
            .copied()
            .unwrap_or(*responsive.base()),
        Point::Wide => responsive
            .wide()
            .or_else(|| responsive.content())
            .or_else(|| responsive.compact())
            .copied()
            .unwrap_or(*responsive.base()),
    }
}

fn typography(theme: &Theme) -> [(&'static str, &TextStyle); 9] {
    [
        ("body", &theme.typography.body),
        ("small", &theme.typography.small),
        ("label", &theme.typography.label),
        ("navigation", &theme.typography.navigation),
        ("heading-1", &theme.typography.heading_1),
        ("heading-2", &theme.typography.heading_2),
        ("heading-3", &theme.typography.heading_3),
        ("hero-lead", &theme.typography.hero_lead),
        ("card-title", &theme.typography.card_title),
    ]
}

fn write_sidebar(css: &mut String, mode: SidebarMode) {
    declaration(css, "sidebar-display", mode.display());
    declaration(css, "sidebar-position", mode.position());
    declaration(css, "sidebar-order", mode.order());
}

fn write_header_mode(css: &mut String, mode: HeaderMode) {
    declaration(css, "header-display", mode.display());
    declaration(css, "header-grid-template", mode.columns());
}

fn declaration(css: &mut String, name: &str, value: impl std::fmt::Display) {
    writeln!(css, "  --mambo-{name}: {value};").unwrap();
}

fn push_override<T>(
    output: &mut Vec<(String, String)>,
    name: String,
    responsive: &Responsive<T>,
    point: Point,
    render: impl FnOnce(&T) -> String,
) {
    if let Some(value) = at(responsive, point) {
        output.push((name, render(value)));
    }
}

const fn at<T>(responsive: &Responsive<T>, point: Point) -> Option<&T> {
    match point {
        Point::Compact => responsive.compact(),
        Point::Content => responsive.content(),
        Point::Wide => responsive.wide(),
    }
}

fn quoted(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
