use std::fmt::Write as _;

use crate::accent::{safe_cycle, shuffled_indices, slot_at};
use crate::model::{
    ColorPalette, ColorScheme, HeaderMode, Responsive, SidebarMode, TextStyle, Theme,
};

#[derive(Clone, Copy)]
enum Point {
    Compact,
    Content,
    Wide,
}

impl Point {
    const fn name(self) -> &'static str {
        match self {
            Self::Compact => "compact",
            Self::Content => "content",
            Self::Wide => "wide",
        }
    }
}

pub(crate) fn render(theme: &Theme, accent_seed: u64) -> String {
    let accent_cycle = safe_cycle(&theme.colors.dark, &theme.colors.light, accent_seed)
        .unwrap_or_else(|| shuffled_indices(theme.colors.dark.accents.len(), accent_seed));
    let mut css = String::from("/* Generated by MamboSite. Do not edit. */\n\n");
    for face in &theme.fonts.faces {
        writeln!(css, "@font-face {{").unwrap();
        writeln!(css, "  font-family: \"{}\";", quoted(&face.family)).unwrap();
        writeln!(
            css,
            "  src: url(\"{}\") format(\"{}\");",
            quoted(&face.source),
            face.format.as_css()
        )
        .unwrap();
        writeln!(css, "  font-weight: {};", face.weight).unwrap();
        writeln!(css, "  font-style: {};", face.style.as_css()).unwrap();
        writeln!(css, "  font-display: {};", face.display.as_css()).unwrap();
        writeln!(css, "}}\n").unwrap();
    }

    let default_palette = palette(theme, theme.default_scheme);
    writeln!(
        css,
        ":root,\n[data-theme=\"{}\"] {{",
        theme.default_scheme.as_str()
    )
    .unwrap();
    write_palette(&mut css, theme.default_scheme, default_palette);
    writeln!(css, "}}\n").unwrap();

    for scheme in [ColorScheme::Dark, ColorScheme::Light] {
        if scheme == theme.default_scheme {
            continue;
        }
        writeln!(css, "[data-theme=\"{}\"] {{", scheme.as_str()).unwrap();
        write_palette(&mut css, scheme, palette(theme, scheme));
        writeln!(css, "}}\n").unwrap();
    }

    writeln!(css, ":root {{").unwrap();
    write_base_tokens(&mut css, theme);
    writeln!(css, "}}\n").unwrap();
    write_collection_rules(
        &mut css,
        "",
        *theme.components.collection.max_columns.base(),
        &accent_cycle,
    );
    write_base_columns_rules(&mut css, &accent_cycle);

    for (point, width) in [
        (Point::Compact, theme.breakpoints.compact),
        (Point::Content, theme.breakpoints.content),
        (Point::Wide, theme.breakpoints.wide),
    ] {
        let declarations = responsive_declarations(theme, point);
        writeln!(css, "@media (min-width: {width}px) {{").unwrap();
        if !declarations.is_empty() {
            writeln!(css, "  :root {{").unwrap();
            for (name, value) in declarations {
                writeln!(css, "    --mambo-{name}: {value};").unwrap();
            }
            writeln!(css, "  }}").unwrap();
        }
        write_collection_rules(
            &mut css,
            "  ",
            collection_limit_at(theme, point),
            &accent_cycle,
        );
        write_columns_breakpoint_rule(&mut css, point, &accent_cycle);
        writeln!(css, "}}\n").unwrap();
    }

    css
}

fn palette(theme: &Theme, scheme: ColorScheme) -> &ColorPalette {
    match scheme {
        ColorScheme::Dark => &theme.colors.dark,
        ColorScheme::Light => &theme.colors.light,
    }
}

fn write_palette(css: &mut String, scheme: ColorScheme, palette: &ColorPalette) {
    writeln!(css, "  color-scheme: {};", scheme.as_str()).unwrap();
    for (name, value) in [
        ("background", &palette.background),
        ("surface", &palette.surface),
        ("surface-strong", &palette.surface_strong),
        ("border", &palette.border),
        ("text", &palette.text),
        ("text-muted", &palette.text_muted),
        ("text-subtle", &palette.text_subtle),
        ("brand", &palette.brand),
        ("brand-hover", &palette.brand_hover),
        ("brand-active", &palette.brand_active),
        ("on-brand", &palette.on_brand),
        ("selection", &palette.selection),
        ("focus", &palette.focus),
        ("success", &palette.success),
        ("warning", &palette.warning),
        ("danger", &palette.danger),
        ("header-background", &palette.header_background),
        ("shadow", &palette.shadow),
    ] {
        writeln!(css, "  --mambo-color-{name}: {value};").unwrap();
    }
    for (index, accent) in palette.accents.iter().enumerate() {
        writeln!(css, "  --mambo-color-accent-{}: {accent};", index + 1).unwrap();
    }
}

fn write_base_tokens(css: &mut String, theme: &Theme) {
    for (name, value) in [
        ("font-body", theme.fonts.body.as_str()),
        ("font-heading", theme.fonts.heading.as_str()),
        ("font-mono", theme.fonts.mono.as_str()),
    ] {
        declaration(css, name, value);
    }

    for (name, style) in typography(theme) {
        declaration(css, &format!("type-{name}-size"), style.size.base());
        declaration(css, &format!("type-{name}-line-height"), &style.line_height);
        declaration(css, &format!("type-{name}-weight"), style.weight);
        declaration(
            css,
            &format!("type-{name}-letter-spacing"),
            &style.letter_spacing,
        );
    }

    for (name, value) in [
        ("space-xxs", &theme.spacing.xxs),
        ("space-xs", &theme.spacing.xs),
        ("space-sm", &theme.spacing.sm),
        ("space-md", &theme.spacing.md),
        ("space-lg", &theme.spacing.lg),
        ("space-xl", &theme.spacing.xl),
        ("space-xxl", &theme.spacing.xxl),
        ("space-section", &theme.spacing.section),
        ("width-reading", &theme.widths.reading),
        ("width-normal", &theme.widths.normal),
        ("width-wide", &theme.widths.wide),
        ("width-full", &theme.widths.full),
        ("width-shell", &theme.widths.shell),
        ("width-sidebar", &theme.widths.sidebar),
        ("width-card-min", &theme.widths.card_min),
        ("width-hero-image-min", &theme.widths.hero_image_min),
        ("width-gallery-image-max", &theme.widths.gallery_image_max),
        (
            "dimension-main-top-padding",
            theme.dimensions.main_top_padding.base(),
        ),
        (
            "dimension-header-height",
            theme.dimensions.header_height.base(),
        ),
        ("dimension-header-blur", &theme.dimensions.header_blur),
        ("dimension-toc-offset", theme.dimensions.toc_offset.base()),
        (
            "dimension-hero-min-height",
            &theme.dimensions.hero_min_height,
        ),
        (
            "dimension-control-min-height",
            &theme.dimensions.control_min_height,
        ),
        ("border-thin", &theme.borders.thin),
        ("border-strong", &theme.borders.strong),
        ("border-accent", &theme.borders.accent),
        ("radius-small", &theme.radii.small),
        ("radius-medium", &theme.radii.medium),
        ("radius-large", &theme.radii.large),
        ("radius-pill", &theme.radii.pill),
        ("shadow-small", &theme.shadows.small),
        ("shadow-medium", &theme.shadows.medium),
        ("shadow-large", &theme.shadows.large),
        ("motion-fast", &theme.motion.fast),
        ("motion-normal", &theme.motion.normal),
        ("motion-slow", &theme.motion.slow),
        ("motion-easing", &theme.motion.easing),
    ] {
        declaration(css, name, value);
    }
    declaration(css, "border-style", theme.borders.style.as_css());
    declaration(css, "card-accent", "var(--mambo-color-accent-1)");

    write_base_layout_tokens(css, theme);
}

fn write_base_layout_tokens(css: &mut String, theme: &Theme) {
    for (name, value) in [
        (
            "layout-page-with-sidebar-columns",
            theme.layout.page_with_sidebar_columns.base(),
        ),
        (
            "layout-hero-split-columns",
            theme.layout.hero_split_columns.base(),
        ),
        (
            "layout-list-card-columns",
            theme.layout.list_card_columns.base(),
        ),
        (
            "layout-metadata-columns",
            theme.layout.metadata_columns.base(),
        ),
        (
            "layout-header-inline-padding",
            theme.layout.header_inline_padding.base(),
        ),
        (
            "layout-page-inline-padding",
            theme.layout.page_inline_padding.base(),
        ),
        (
            "layout-footer-inline-padding",
            theme.layout.footer_inline_padding.base(),
        ),
    ] {
        declaration(css, name, value);
    }
    declaration(
        css,
        "layout-footer-direction",
        theme.layout.footer_direction.base().as_css(),
    );

    declaration(
        css,
        "collection-max-columns",
        theme.components.collection.max_columns.base(),
    );
    write_sidebar(css, *theme.components.sidebar.mode.base());
    write_header_mode(css, *theme.components.header.mode.base());
    declaration(
        css,
        "header-clock-display",
        theme.components.header.clock.base().flex_display(),
    );
    declaration(
        css,
        "header-hide-on-scroll",
        u8::from(theme.components.header.hide_on_scroll),
    );
    declaration(css, "header-hide-after", theme.components.header.hide_after);
}

fn responsive_declarations(theme: &Theme, point: Point) -> Vec<(String, String)> {
    let mut declarations = Vec::new();
    for (name, style) in typography(theme) {
        push_override(
            &mut declarations,
            format!("type-{name}-size"),
            &style.size,
            point,
            ToString::to_string,
        );
    }
    for (name, value) in [
        (
            "dimension-main-top-padding",
            &theme.dimensions.main_top_padding,
        ),
        ("dimension-header-height", &theme.dimensions.header_height),
        ("dimension-toc-offset", &theme.dimensions.toc_offset),
        (
            "layout-page-with-sidebar-columns",
            &theme.layout.page_with_sidebar_columns,
        ),
        (
            "layout-hero-split-columns",
            &theme.layout.hero_split_columns,
        ),
        ("layout-list-card-columns", &theme.layout.list_card_columns),
        ("layout-metadata-columns", &theme.layout.metadata_columns),
        (
            "layout-header-inline-padding",
            &theme.layout.header_inline_padding,
        ),
        (
            "layout-page-inline-padding",
            &theme.layout.page_inline_padding,
        ),
        (
            "layout-footer-inline-padding",
            &theme.layout.footer_inline_padding,
        ),
    ] {
        push_override(
            &mut declarations,
            name.to_owned(),
            value,
            point,
            ToString::to_string,
        );
    }
    push_override(
        &mut declarations,
        "collection-max-columns".to_owned(),
        &theme.components.collection.max_columns,
        point,
        ToString::to_string,
    );
    if let Some(mode) = at(&theme.components.sidebar.mode, point) {
        declarations.push(("sidebar-display".to_owned(), mode.display().to_owned()));
        declarations.push(("sidebar-position".to_owned(), mode.position().to_owned()));
        declarations.push((
            "sidebar-inline-display".to_owned(),
            mode.inline_display().to_owned(),
        ));
        declarations.push((
            "sidebar-rail-display".to_owned(),
            mode.rail_display().to_owned(),
        ));
    }
    if let Some(mode) = at(&theme.components.header.mode, point) {
        declarations.push(("header-display".to_owned(), mode.display().to_owned()));
        declarations.push(("header-grid-template".to_owned(), mode.columns().to_owned()));
        declarations.push((
            "header-navigation-display".to_owned(),
            mode.navigation_display().to_owned(),
        ));
        declarations.push((
            "header-navigation-direction".to_owned(),
            mode.navigation_direction().to_owned(),
        ));
        declarations.push((
            "header-navigation-position".to_owned(),
            mode.navigation_position().to_owned(),
        ));
        declarations.push((
            "header-toggle-display".to_owned(),
            mode.toggle_display().to_owned(),
        ));
    }
    if let Some(visibility) = at(&theme.components.header.clock, point) {
        declarations.push((
            "header-clock-display".to_owned(),
            visibility.flex_display().to_owned(),
        ));
    }
    if let Some(direction) = at(&theme.layout.footer_direction, point) {
        declarations.push((
            "layout-footer-direction".to_owned(),
            direction.as_css().to_owned(),
        ));
    }
    declarations
}

fn write_collection_rules(css: &mut String, indent: &str, maximum: u8, cycle: &[usize]) {
    for requested in 1..=6 {
        let effective = requested.min(maximum);
        writeln!(
            css,
            "{indent}[data-mambo-collection][data-columns=\"{requested}\"] {{ --mambo-collection-columns: {effective}; }}"
        )
        .unwrap();
    }
    for effective in 1..=maximum.min(6) {
        let containers = (1..=6)
            .filter(|&requested| requested.min(maximum) == effective)
            .map(|requested| format!("[data-mambo-collection][data-columns=\"{requested}\"]"))
            .collect::<Vec<_>>();
        let container = if containers.len() == 1 {
            containers[0].clone()
        } else {
            format!(":is({})", containers.join(", "))
        };
        write_accent_grid_rules(css, indent, &container, usize::from(effective), cycle);
    }
    writeln!(css).unwrap();
}

fn write_base_columns_rules(css: &mut String, cycle: &[usize]) {
    writeln!(
        css,
        "[data-mambo-columns][data-collapse=\"compact\"],\n[data-mambo-columns][data-collapse=\"content\"],\n[data-mambo-columns][data-collapse=\"wide\"] {{\n  --mambo-layout-columns-template: minmax(0, 1fr);\n}}"
    )
    .unwrap();
    writeln!(
        css,
        "[data-mambo-columns][data-collapse=\"never\"] {{\n  --mambo-layout-columns-template: repeat(var(--mambo-column-count, 2), minmax(0, 1fr));\n}}\n"
    )
    .unwrap();
    write_accent_grid_rules(
        css,
        "",
        "[data-mambo-columns]:not([data-collapse=\"never\"])",
        1,
        cycle,
    );
    for columns in 1..=4 {
        write_accent_grid_rules(
            css,
            "",
            &format!("[data-mambo-columns][data-collapse=\"never\"][data-columns=\"{columns}\"]"),
            columns,
            cycle,
        );
    }
    writeln!(css).unwrap();
}

fn write_columns_breakpoint_rule(css: &mut String, point: Point, cycle: &[usize]) {
    writeln!(
        css,
        "  [data-mambo-columns][data-collapse=\"{}\"] {{",
        point.name()
    )
    .unwrap();
    writeln!(
        css,
        "    --mambo-layout-columns-template: repeat(var(--mambo-column-count, 2), minmax(0, 1fr));"
    )
    .unwrap();
    writeln!(css, "  }}").unwrap();
    for columns in 2..=4 {
        write_accent_grid_rules(
            css,
            "  ",
            &format!(
                "[data-mambo-columns][data-collapse=\"{}\"][data-columns=\"{columns}\"]",
                point.name()
            ),
            columns,
            cycle,
        );
    }
}

fn write_accent_grid_rules(
    css: &mut String,
    indent: &str,
    container: &str,
    columns: usize,
    cycle: &[usize],
) {
    let period = cycle.len() * columns;
    for slot in 0..cycle.len() {
        let selectors = (0..period)
            .filter(|&index| slot_at(cycle, columns, index) == slot)
            .map(|index| {
                format!(
                    "{indent}{container} > [data-mambo-accent-item]:nth-child({period}n + {})",
                    index + 1
                )
            })
            .collect::<Vec<_>>();
        writeln!(
            css,
            "{} {{ --mambo-card-accent: var(--mambo-color-accent-{}); }}",
            selectors.join(",\n"),
            slot + 1
        )
        .unwrap();
    }
}

fn collection_limit_at(theme: &Theme, point: Point) -> u8 {
    let responsive = &theme.components.collection.max_columns;
    match point {
        Point::Compact => responsive.compact().copied().unwrap_or(*responsive.base()),
        Point::Content => responsive
            .content()
            .or_else(|| responsive.compact())
            .copied()
            .unwrap_or(*responsive.base()),
        Point::Wide => responsive
            .wide()
            .or_else(|| responsive.content())
            .or_else(|| responsive.compact())
            .copied()
            .unwrap_or(*responsive.base()),
    }
}

fn typography(theme: &Theme) -> [(&'static str, &TextStyle); 9] {
    [
        ("body", &theme.typography.body),
        ("small", &theme.typography.small),
        ("label", &theme.typography.label),
        ("navigation", &theme.typography.navigation),
        ("heading-1", &theme.typography.heading_1),
        ("heading-2", &theme.typography.heading_2),
        ("heading-3", &theme.typography.heading_3),
        ("hero-lead", &theme.typography.hero_lead),
        ("card-title", &theme.typography.card_title),
    ]
}

fn write_sidebar(css: &mut String, mode: SidebarMode) {
    declaration(css, "sidebar-display", mode.display());
    declaration(css, "sidebar-position", mode.position());
    declaration(css, "sidebar-inline-display", mode.inline_display());
    declaration(css, "sidebar-rail-display", mode.rail_display());
}

fn write_header_mode(css: &mut String, mode: HeaderMode) {
    declaration(css, "header-display", mode.display());
    declaration(css, "header-grid-template", mode.columns());
    declaration(css, "header-navigation-display", mode.navigation_display());
    declaration(
        css,
        "header-navigation-direction",
        mode.navigation_direction(),
    );
    declaration(
        css,
        "header-navigation-position",
        mode.navigation_position(),
    );
    declaration(css, "header-toggle-display", mode.toggle_display());
}

fn declaration(css: &mut String, name: &str, value: impl std::fmt::Display) {
    writeln!(css, "  --mambo-{name}: {value};").unwrap();
}

fn push_override<T>(
    output: &mut Vec<(String, String)>,
    name: String,
    responsive: &Responsive<T>,
    point: Point,
    render: impl FnOnce(&T) -> String,
) {
    if let Some(value) = at(responsive, point) {
        output.push((name, render(value)));
    }
}

const fn at<T>(responsive: &Responsive<T>, point: Point) -> Option<&T> {
    match point {
        Point::Compact => responsive.compact(),
        Point::Content => responsive.content(),
        Point::Wide => responsive.wide(),
    }
}

fn quoted(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::write_accent_grid_rules;
    use crate::accent::{safe_cycle, slot_at};
    use crate::model::Theme;

    #[test]
    fn generated_grid_rules_follow_the_safe_cycle() {
        let theme = Theme::default();
        let cycle = safe_cycle(&theme.colors.dark, &theme.colors.light, 42).unwrap();

        for columns in 1..=6 {
            let mut css = String::new();
            write_accent_grid_rules(&mut css, "", "[data-grid]", columns, &cycle);
            let period = cycle.len() * columns;
            for index in 0..period {
                let selector = format!(
                    "[data-grid] > [data-mambo-accent-item]:nth-child({period}n + {})",
                    index + 1
                );
                let rule = &css[css.find(&selector).unwrap()..];
                let rule = &rule[..rule.find('}').unwrap()];
                assert!(rule.contains(&format!(
                    "--mambo-card-accent: var(--mambo-color-accent-{})",
                    slot_at(&cycle, columns, index) + 1
                )));
            }
        }
    }
}
