// Generated by `node script/sync_mambocolour.mjs`; do not edit.
// Source: MamboColour's positional `css` provider command.

use crate::model::ColorPalette;

pub(crate) fn dark() -> ColorPalette {
    ColorPalette {
        background: "#181615".to_owned(),
        surface: "#24201e".to_owned(),
        surface_strong: "#3d3633".to_owned(),
        border: "#3d3633".to_owned(),
        text: "#faf7f2".to_owned(),
        text_muted: "#d5c9b8".to_owned(),
        text_subtle: "#969085".to_owned(),
        brand: "#ff6b57".to_owned(),
        brand_hover: "#ffa775".to_owned(),
        brand_active: "#e65235".to_owned(),
        on_brand: "#181615".to_owned(),
        selection: "#d44b36".to_owned(),
        focus: "#d3a774".to_owned(),
        success: "#64705e".to_owned(),
        warning: "#d3a774".to_owned(),
        danger: "#d44b36".to_owned(),
        header_background: "rgb(24 22 21 / 92%)".to_owned(),
        shadow: "rgb(22 20 19 / 28%)".to_owned(),
        accents: [
            "#9cbaac", "#ffa775", "#c2cca8", "#8b9cbd", "#e08a4f", "#bf8087",
        ]
        .map(str::to_owned)
        .to_vec(),
    }
}

pub(crate) fn light() -> ColorPalette {
    ColorPalette {
        background: "#faf7f2".to_owned(),
        surface: "#f3ece2".to_owned(),
        surface_strong: "#e1d5c3".to_owned(),
        border: "#e1d5c3".to_owned(),
        text: "#1c1111".to_owned(),
        text_muted: "#5c4d4a".to_owned(),
        text_subtle: "#765d3f".to_owned(),
        brand: "#a93622".to_owned(),
        brand_hover: "#822727".to_owned(),
        brand_active: "#5e1e17".to_owned(),
        on_brand: "#faf7f2".to_owned(),
        selection: "#a93622".to_owned(),
        focus: "#822727".to_owned(),
        success: "#5c705a".to_owned(),
        warning: "#d3a774".to_owned(),
        danger: "#a93622".to_owned(),
        header_background: "rgb(250 247 242 / 92%)".to_owned(),
        shadow: "rgb(28 17 17 / 14%)".to_owned(),
        accents: [
            "#6b8c85", "#de8554", "#8fa382", "#4e687d", "#b86935", "#8c5258",
        ]
        .map(str::to_owned)
        .to_vec(),
    }
}
