use serde::Serialize;

use crate::model::Theme;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ThemeMetadata<'a> {
    schema_version: u32,
    id: &'a str,
    default_scheme: &'a str,
    schemes: [&'static str; 2],
    breakpoints: BreakpointMetadata,
    behavior: BehaviorMetadata,
}

#[derive(Serialize)]
struct BreakpointMetadata {
    compact: u32,
    content: u32,
    wide: u32,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct BehaviorMetadata {
    header_hide_on_scroll: bool,
    header_hide_after: u32,
}

pub(crate) fn render(theme: &Theme) -> String {
    let metadata = ThemeMetadata {
        schema_version: theme.schema,
        id: &theme.id,
        default_scheme: theme.default_scheme.as_str(),
        schemes: ["dark", "light"],
        breakpoints: BreakpointMetadata {
            compact: theme.breakpoints.compact,
            content: theme.breakpoints.content,
            wide: theme.breakpoints.wide,
        },
        behavior: BehaviorMetadata {
            header_hide_on_scroll: theme.components.header.hide_on_scroll,
            header_hide_after: theme.components.header.hide_after,
        },
    };
    let json = serde_json::to_string_pretty(&metadata)
        .expect("the fixed theme metadata representation is serializable");
    format!(
        "// Generated by MamboSite. Do not edit.\n\nexport const theme = {json} as const;\n\nexport type GeneratedTheme = typeof theme;\n"
    )
}
